    - name: Send status to Discord
      uses: nebularg/actions-discord-webhook@v1
      with:
        webhook_url: ${{ secrets.discord_webhook_url }} # required
        status: ${{ job.status }} # optional, this is the default
      if: always() # or failure() or success()
