name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  send-status:
    runs-on: ubuntu-latest
    steps:
      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: https://discord.com/api/webhooks/13
          status: ${{ job.status }}
        if: always()
