name: Discord Webhook

on: [push]

jobs:
  report-status:

    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Message
      uses: EhsanFox/djs-actions@0.1.0
      with:
          id: ${{ secrets.WEBHOOK_ID }}
          token: ${{ secrets.WEBHOOK_TOKEN }}
          username: Github Actions
          avatar: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
