name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  send-status:
    runs-on: ubuntu-latest
    steps:
      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        env:
          WEBHOOK_URL: ${{ secrets.DISCORDWEBHOOKLINK }}
        with:
          status: ${{ job.status }}
        if: always()
